### ISSUE TITLE
PHP Warning:  fopen(/out/courses-list_1619982130.xlsx): failed to open stream: No such file or directory in C:\xampp\htdocs\udemy-export-master\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\BaseWriter.php on line 111

### ISSUE THREAD

**Issue by lixqpxil** [SirNarsh/udemy-export#1]
when i am running the php main access_token, the cmd shows the course enrolled and other details, but when the file is created i get the above error.

**Comment by SirNarsh** [comment]
This is tested to run on docker, the path of output is `/out/` which won't work for windows... if you don't want to use the docker command as in readme, then you'll need to modify the output path
`docker run --rm -v ${PWD}:/out sirnarsh/udemy-export TOKEN_HERE`
